import { router, json, error, db, ai } from '@appdeploy/sdk';

type ResumeRecord = { title: string; template: string; profile: Record<string, unknown>; experience: unknown[]; education: unknown[]; skills: string[]; projects: unknown[]; achievements: unknown[]; certifications: string[]; codingProfiles: string[]; additional: string[]; updatedAt: string };
type ImportPayload = { text?: string; images?: { data: string; mimeType: string }[] };
type KeywordSuggestion = { keyword: string; evidence: string };
type JobMatchResult = { beforeScore: number; afterScore: number; matchedKeywords: string[]; missingKeywords: string[]; changes: string[]; jobTitle?: string; resume: Record<string, unknown> };
function keywordScore(text: string, keywords: string[]) { const normalized = text.toLowerCase(); if (!keywords.length) return 0; const matched = keywords.filter(k => normalized.includes(k.toLowerCase())).length; return Math.round((matched / keywords.length) * 100); }
const table = 'resumes';
const scoped = (owner: string) => `${owner}:`;
export const handler = router({
  'GET /api/_healthcheck': [async () => json({ message: 'Success' })],
  'GET /api/resumes': [async ({ query }) => { const owner = query.owner || 'demo'; const { items } = await db.list<ResumeRecord>(table, { limit: 50 }); return json({ resumes: items.filter(r => r.title.startsWith(scoped(owner))).map(r => ({ ...r, title: r.title.slice(scoped(owner).length) })) }); }],
  'POST /api/resumes': [async ({ body }) => { const input = body as Omit<ResumeRecord, 'updatedAt'>; if (!input || typeof input !== 'object' || !input.title?.trim()) return error('Resume name is required', 400); const record = { ...input, title: `${scoped('demo')}${input.title.trim()}`, updatedAt: new Date().toISOString() } as ResumeRecord; const [id] = await db.add(table, [record]); if (!id) return error('Could not save resume', 500); return json({ resume: { ...record, id, title: input.title.trim() } }, 201); }],
  'PUT /api/resumes/:id': [async ({ params, body }) => { const current = (await db.get<ResumeRecord>(table, [params.id]))[0]; if (!current) return error('Resume not found', 404); const input = body as Omit<ResumeRecord, 'updatedAt'>; if (!input.title?.trim()) return error('Resume name is required', 400); const next = { ...input, title: `${scoped('demo')}${input.title.trim()}`, updatedAt: new Date().toISOString() } as ResumeRecord; const [ok] = await db.update(table, [{ id: params.id, record: next as Record<string, unknown> }]); if (!ok) return error('Could not update resume', 500); return json({ resume: { ...next, id: params.id, title: input.title.trim() } }); }],
  'DELETE /api/resumes/:id': [async ({ params }) => { const [ok] = await db.delete(table, [params.id]); if (!ok) return error('Resume not found', 404); return json({ deleted: true }); }],
  'POST /api/ai/bullets': [async ({ body }) => { const p = body as { kind?: string; title?: string; stack?: string; description?: string; role?: string; skills?: string[] }; if (!p?.title?.trim()) return error('Title is required', 400); try { const r = await ai.generate({ system: 'Write exactly three resume bullets. Each bullet must be a separate string, start with a strong action verb, state what was done, mention an implementation detail, and end with a concrete engineering outcome. Use only supplied facts. Never invent metrics, users, revenue, employers, dates or technologies. Keep each under 28 words.', prompt: `Type: ${p.kind}\nTitle: ${p.title}\nStack: ${p.stack || 'not provided'}\nDescription: ${p.description || 'not provided'}\nTarget role: ${p.role || 'Software Engineer'}\nKnown skills: ${(p.skills || []).join(', ')}`, schema: { type: 'object', properties: { bullets: { type: 'array', minItems: 3, maxItems: 3, items: { type: 'string' } } }, required: ['bullets'] }, maxTokens: 900, temperature: .25, thinkingMode: 'FAST' }); const out = JSON.parse(r.text) as { bullets?: string[] }; const bullets = (out.bullets || []).filter(Boolean).slice(0, 3); if (bullets.length !== 3) return error('AI did not return three bullets', 502); return json({ bullets }); } catch (e) { console.error('bullet generation failed', e); return error('AI bullet generation failed', 502); } }],
  'POST /api/ai/quality-check': [async ({ body }) => { const p = body as { resume?: unknown }; if (!p?.resume) return error('Resume is required', 400); try { const r = await ai.generate({ system: 'Review a resume for internal inconsistencies, impossible date ranges, malformed contact links, placeholder text, unsupported or suspiciously precise claims, duplicate content, vague wording and formatting risks. Do not declare a fact false without evidence. Return concise JSON issues with field, issue, fix and severity.', prompt: JSON.stringify(p.resume), schema: { type: 'object', properties: { issues: { type: 'array', maxItems: 8, items: { type: 'object', properties: { field: { type: 'string' }, issue: { type: 'string' }, fix: { type: 'string' }, severity: { type: 'string', enum: ['high','medium','low'] } }, required: ['field','issue','fix','severity'] } } }, required: ['issues'] }, maxTokens: 1300, temperature: .2, thinkingMode: 'FAST' }); return json(JSON.parse(r.text)); } catch (e) { console.error('quality check failed', e); return error('AI quality check failed', 502); } }],
  'POST /api/ai/import-resume': [async ({ body }) => { const p = body as ImportPayload; if (!p?.text?.trim() && !(p.images && p.images.length)) return error('Resume content is required', 400); try { const r = await ai.generate({ system: 'Extract the uploaded resume into the requested structured schema. Read visible text from supplied page images when present. Preserve facts; never invent missing fields. Use the exact wording when practical. Split experience, education, skills, projects, achievements, certifications, coding profiles and additional information. Return JSON only.', prompt: `${p.text?.slice(0, 30000) || ''}\n\nIf page images are provided, use them to recover text that could not be extracted from the PDF.`, images: (p.images || []).slice(0, 4), schema: { type: 'object', properties: { resume: { type: 'object', properties: { title:{type:'string'}, template:{type:'string'}, profile:{type:'object'}, experience:{type:'array'}, education:{type:'array'}, skills:{type:'array'}, projects:{type:'array'}, achievements:{type:'array'}, certifications:{type:'array'}, codingProfiles:{type:'array'}, additional:{type:'array'} }, required:['profile','experience','education','skills','projects','achievements','certifications','codingProfiles','additional'] } }, required:['resume'] }, maxTokens: 6500, temperature: .1, thinkingMode: 'FAST' }); return json(JSON.parse(r.text)); } catch (e) { console.error('resume import failed', e); return error('AI resume import failed', 502); } }],
  'POST /api/ai/job-match': [async ({ body }) => { const p = body as { resume?: Record<string, unknown>; jobText?: string; jobUrl?: string }; if (!p?.resume || (!p.jobText?.trim() && !p.jobUrl?.trim())) return error('Resume and job description or URL are required', 400); try { let jd = p.jobText || ''; let jobTitle = ''; if (p.jobUrl?.trim()) { const url = p.jobUrl.trim(); if (!/^https?:\/\//i.test(url)) return error('Job URL must start with http:// or https://', 400); const scraped = await ai.scrape({ url }); if (scraped.status >= 400 || !scraped.text) return error('Could not read that job URL. Paste the job description instead.', 502); jobTitle = scraped.title || ''; jd = `${scraped.title || 'Job description'}\n${scraped.text}`; } const originalText = JSON.stringify(p.resume); const r = await ai.generate({ system: 'Compare this resume with the job description. The resume is locked: do not rewrite, paraphrase, reorder, reformat or replace any existing content. Identify only job keywords genuinely supported by facts already present in the resume. For every suggested keyword, provide an exact evidence phrase copied from the resume. Do not infer experience that is not present. Also identify resume keywords that are clearly irrelevant, generic or misleading for this specific job and should be considered for removal. Return concise JSON only.', prompt: `RESUME:\n${originalText}\n\nJOB DESCRIPTION:\n${jd.slice(0, 30000)}`, schema: { type: 'object', properties: { jobKeywords:{type:'array',items:{type:'string'}}, supportedKeywords:{type:'array',items:{type:'object',properties:{keyword:{type:'string'},evidence:{type:'string'}},required:['keyword','evidence']}}, missingKeywords:{type:'array',items:{type:'string'}}, removeKeywords:{type:'array',items:{type:'string'}}, jobTitle:{type:'string'} }, required:['jobKeywords','supportedKeywords','missingKeywords','removeKeywords'] }, maxTokens: 3200, temperature: .1, thinkingMode: 'FAST' }); const out = JSON.parse(r.text) as { jobKeywords?: string[]; supportedKeywords?: KeywordSuggestion[]; missingKeywords?: string[]; jobTitle?: string; removeKeywords?: string[] }; const jobKeywords = [...new Set((out.jobKeywords || []).map(k => k.trim()).filter(Boolean))]; const beforeScore = keywordScore(originalText, jobKeywords); const changes = out.missingKeywords || []; return json({ beforeScore, afterScore: beforeScore, matchedKeywords: jobKeywords.filter(k => originalText.toLowerCase().includes(k.toLowerCase())), missingKeywords: out.removeKeywords || [], changes, jobTitle: out.jobTitle || jobTitle, resume: p.resume } as JobMatchResult); } catch (e) { console.error('job match failed', e); return error('Job matching failed. Try pasting the job description.', 502); } }]
});
